version: "3"
services:
    database-local:
        image: postgres
        restart: always
        container_name: database-local
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "database-local"
            POSTGRES_PASSWORD: "123456"
        ports:
            - 15432:5432
